[workspace]
members = [
  "core",
  "python",
  "server",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Vladimir Alinsky <Vladimir@Alinsky.tech>", "Vsevolod Zolotov <vsezold@gmail.com>", "Cumstantin Alaev <alaev@dog.cum>"]
