version: "3.9"

services:
  space-drive-game:
    image: space-drive-game:latest
    container_name: space-drive-game
    build:
      context: .
    ports:
      - "3333:3333/tcp"

  space-drive-visualizer:
    image: vsezol/space-drive-visualizer:latest
    container_name: space-drive-visualizer
    depends_on:
      - space-drive-game
