[package]
name = "space_drive_game_core"

workspace = ".."

version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
name = "space_drive_game_core"

[dependencies]
rand = "0.8.5"
noise = "0.9.0"
