[package]
name = "space_drive_game_server"

workspace = ".."

version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
log = "0.4.20"
env_logger = "0.11.2"

[dependencies.space_drive_game_core]
path = "../core"
