[package]
name = "space-drive-game"

workspace = ".."

version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
name = "space_drive_game"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.3"

[dependencies.space_drive_game_core]
path = "../core"
