class Map:
    width: int
    height: int
    def __new__(cls, width: int, height: int, barriers_amount: int, max_barrier_radius: int) -> Map: ...
    def get_barriers(self) -> tuple[int, int, int]: ...
    def get_free_point(self) -> tuple[int, int]: ...

class Player:
    x: float
    y: float
    direction: float
    def __new__(cls, x: float, y: float) -> Player: ...
    def rotate(self, direction: float) -> None: ...
    def forward(self) -> None: ...

class Game: ...
 