from typing import Union


class Map:
    def __new__(cls, width: int, height: int, barriers_amount: int, max_barrier_radius: int) -> Map: ...
    def get_barriers(self) -> tuple[int, int, int]: ...
    def get_free_point(self) -> tuple[int, int]: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...


class Player:
    def __new__(cls, x: float, y: float, direction: Union[float, None] = None) -> Player: ...
    def rotate(self, direction: float) -> None: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def direction(self) -> float: ...


class Game:
    def __new__(cls, map: Map) -> Game: ...
    def register_player(self, player: Player) -> None: ...
    def process() -> None: ...
 