name: Core CI

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
    contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test core
    steps:
      - uses: actions/checkout@v4
      - run: cargo test --package space_drive_game_core
